#Autogenerated by ReportLab guiedit do not edit
from reportlab.graphics.shapes import Drawing, _DrawingEditorMixin
from reportlab.graphics.charts.lineplots import GridLinePlot

class GridLinePlotDrawing(_DrawingEditorMixin,Drawing):
	def __init__(self,width=400,height=200,*args,**kw):
		Drawing.__init__(*(self,width,height)+args, **kw)
		self._add(self,GridLinePlot(),name='plot',validate=None,desc=None)
		self.plot.y  = 20
		self.plot.x  = 30
		self.plot.yValueAxis.minimumTickSpacing  = 15
		self.plot.yValueAxis.maximumTicks  = 5
		self.plot.yValueAxis.leftAxisPercent  = 0
		self.width       = 230
		self.height      = 115

if __name__=="__main__": #NORUNTESTS
	GridLinePlotDrawing().save(formats=['pdf'],outDir='.',fnRoot=None)